### ISSUE TITLE
Possible overlap/collaboration with other project

### ISSUE THREAD

**Issue by abenhamdine** [calebmer/pg-sql#1]
Hi,

I just found out your module totally by accident, and just want to point out that the following project seems to follow similar goals : 
https://github.com/felixfbecker/node-sql-template-strings

Note that I'm not involved in this project in any way, I just use this module for several months, and it works fine.

**Comment by calebmer** [comment]
Cool, good to know. It would have been helpful to know about this module a while ago 😉

Although it doesn't solve the needs I was feeling for [PostGraphQL](https://github.com/calebmer/postgraphql) (where the first implementation of this module [lives](https://github.com/calebmer/postgraphql/blob/2b245daace3e25b9eb6fd73e6c1a09ba0e408969/src/postgres/utils/sql.ts). Specifically the ability to compose SQL queries in a safe fashion to avoid SQL injection and keep the order of a `values` array. I also really wanted an escape mechanism for identifiers and a minification step so I could add [documentation](https://github.com/calebmer/postgraphql/blob/2b245daace3e25b9eb6fd73e6c1a09ba0e408969/src/postgres/inventory/collection/PgCollectionKey.ts#L135) to long queries.

Turns out I still needed those properties outside of PostGraphQL in my work, so `pg-sql` was born 😊

It solves my needs almost perfectly, so I'm very happy with it. It was by accident that I may have introduced a little overlap 😉. If someone wants to make a PR to `sql-template-strings` making this module obsolete, I'd be all for it!

**Comment by abenhamdine** [comment]
Ah yes, I better understand the rationale of this project.
Thx for your detailled answer ! 😊 
I will try to have a look for the additional features this project has compared to `sql-templated-strings` and if I can make some PR.
